### ISSUE TITLE
Permission for chinese translation

### ISSUE THREAD

**Issue by ika-twb** [bigskysoftware/grugbrain.dev#4]
article very good, me so inspired
me want share article other chinese grugs
some chinese grugs not good english, no understand, me sad
me chinese very good, me native chinese since birth
me want make it good in chinese, good to share other chinese grugs
repo no license, me confused
ask for permission, pretty plz

**Comment by corlaez** [comment]
https://github.com/bigskysoftware/grugbrain.dev/blob/master/LICENSE

**Comment by ika-twb** [comment]
mission complete, issue close
